---
title: "egg clean up"
author: "An Bui"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 0. Set up
```{r libraries}
library(tidyverse)
library(here)
library(janitor)
library(calecopal)
library(ggforce)
```

```{r data}
egg_shape <- read_csv(here::here("data", "Stoddard_et_al-egg_shape.csv")) %>% 
  clean_names() %>% 
  dplyr::select(1:7)
```

### 1. Cleaning
```{r}
ord <- egg_shape %>% 
  group_by(order) %>% 
  summarize(mean_asym = mean(asymmetry),
            sd_asym = sd(asymmetry),
            mean_elli = mean(ellipticity),
            sd_elli = sd(ellipticity))
```

### 2. Figures
```{r elli-asym}
n_colors <- nrow(egg_shape)

elli_asym <- ggplot(egg_shape, aes(x = ellipticity, y = asymmetry)) +
  geom_point(aes(col = ellipticity), alpha = 0.3, size = 3) +
  scale_color_gradientn(colors = cal_palette(name = "chaparral1", n = n_colors, type = "continuous")) +
  geom_ellipse(aes(x0 = 0.4, y0 = 0.2, a = 0.5, b = 0.3, angle = 45))

elli_asym
```








